---
--- Generated by Luanalysis
--- Created by Sfy12.
--- DateTime: 2023/6/12 1:21
---

--获取锁中的线程标识 get key
local id = redis.call('get', KEYS[1])
--比较线程标识和锁的标识是否一致
if(id == ARGV[1]) then
    --释放锁 del key
    return redis.call('del', KEYS[1])
end
return 0
